import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});fs.mkdirSync('artifacts/activity-hud',{recursive:true});const errors=[];
try{for(const [width,height] of [[1440,900],[390,844],[768,1024]]){
 const p=await browser.newPage({viewport:{width,height},isMobile:width<900,hasTouch:width<900});p.on('pageerror',e=>errors.push(e.message));
 await p.goto('http://127.0.0.1:4180/?geodesicQA');await p.waitForFunction(()=>window.geodesicQA);
 assert.equal(await p.locator('.demo-badge').count(),0);assert.equal(await p.locator('#hint').isVisible(),false);assert.equal(await p.locator('.example-activity').count(),4);
 await p.locator('#rotationToggle').click();assert.equal(await p.locator('#rotationToggle').getAttribute('aria-pressed'),'false');await p.locator('#rotationToggle').click();assert.equal(await p.locator('#rotationToggle').getAttribute('aria-pressed'),'true');assert.equal(await p.locator('#rotateLeft').count(),0);
 await p.locator('#toggleHexSearch').click();await p.locator('#hexSearchInput').fill('Nike');await p.locator('#companyResults button').click();await p.locator('#placementInspector').waitFor({state:'visible'});
 assert.equal(await p.locator('#inspectorHex').count(),0);assert.match(await p.locator('#inspectorInfo').textContent(),/12,429/);assert.equal((await p.locator('#placementInspector').textContent()).includes('Example'),false);assert.equal(await p.locator('#inspectorDate').textContent(),'08/08/26');assert.equal(await p.locator('#pinInspector svg').count(),0);
 await p.screenshot({path:`artifacts/activity-hud/${width}-details.png`});assert.equal(await p.locator('#inspectorAudience').count(),0);assert.equal(await p.locator('.activity-icon svg').count(),4);const before=await p.locator('#placementInspector').boundingBox();await p.locator('#showNearby').click();const after=await p.locator('#placementInspector').boundingBox();assert.equal(before.height,after.height);await p.screenshot({path:`artifacts/activity-hud/${width}-hud.png`});await p.keyboard.press('Escape');assert.equal(await p.locator('#showNearby').getAttribute('aria-expanded'),'false');assert.equal(await p.locator('#showNearby').evaluate(e=>e===document.activeElement),true);
 await p.locator('.brand').click();await p.waitForTimeout(2400);const home=await p.evaluate(()=>window.geodesicQA.state());assert.ok(Math.abs(home.orientation[3])>.99);const wideSpeed=home.rotationSpeed;
 const id=await p.evaluate(()=>window.geodesicQA.available);await p.evaluate(id=>window.geodesicQA.focus(id,.3),id);await p.waitForTimeout(300);assert.ok(await p.evaluate(()=>window.geodesicQA.state().rotationSpeed)<wideSpeed*.2);
 const point=await p.evaluate(id=>window.geodesicQA.screen(id),id);await p.mouse.click(point.x,point.y);await p.locator('#claimCell').waitFor({state:'visible'});assert.equal(await p.locator('#cellOwner').isVisible(),false);assert.match(await p.locator('#cellNumber').textContent(),/^Hexagon #/);
 await p.locator('#homeView').click();await p.waitForTimeout(2400);await p.screenshot({path:`artifacts/activity-hud/${width}-home.png`});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.close();
}assert.deepEqual(errors,[]);console.log('Activity, HUD, controls, home orientation and close-zoom speed passed at desktop/mobile/tablet widths');}finally{await browser.close();}
